AWSTemplateFormatVersion: '2010-09-09'
Description: Create an EKS Cluster (Microcks Cluster) with a managed node group in the default VPC

Parameters:
  ClusterName:
    Type: String
    Default: microcks-cluster

  KubernetesVersion:
    Type: String
    Default: '1.32'

  NodeInstanceType:
    Type: String
    Default: t3.medium

  NodeGroupName:
    Type: String
    Default: microcks-nodes

  DesiredCapacity:
    Type: Number
    Default: 2

  MinSize:
    Type: Number
    Default: 1

  MaxSize:
    Type: Number
    Default: 3

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Comma-separated list of public subnet IDs (e.g., from default VPC)

Resources:
  EKSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: eks.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref ClusterName
      Version: !Ref KubernetesVersion
      RoleArn: !GetAtt EKSClusterRole.Arn
      ResourcesVpcConfig:
        SubnetIds: !Ref SubnetIds

  NodeInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: ec2.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
      - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy

  NodeGroup:
    Type: AWS::EKS::Nodegroup
    DependsOn: EKSCluster
    Properties:
      NodegroupName: !Ref NodeGroupName
      ClusterName: !Ref ClusterName
      NodeRole: !GetAtt NodeInstanceRole.Arn
      Subnets: !Ref SubnetIds
      ScalingConfig:
        DesiredSize: !Ref DesiredCapacity
        MinSize: !Ref MinSize
        MaxSize: !Ref MaxSize
      InstanceTypes:
      - !Ref NodeInstanceType
      AmiType: AL2_x86_64
      DiskSize: 20

Outputs:
  ClusterName:
    Value: !Ref ClusterName
  ClusterEndpoint:
    Value: !GetAtt EKSCluster.Endpoint
  ClusterARN:
    Value: !GetAtt EKSCluster.Arn
